### ISSUE TITLE
Suggestion: move to pbdmms anyways

### ISSUE THREAD

**Issue by richelbilderbeek** [christophnetz/iPrey#2]
I think it would be more gezellig if you'd join our code in `pbdmms` anyways. It simplifies maintenance as well. 

Tip: reply with `@richelbilderbeek` and I'll get notified sooner than by email.

**Comment by richelbilderbeek** [comment]
Also, pick a namespace/branch name of four chacters, e.g. `cine`, `toph`, `netz` or something else.

**Comment by christophnetz** [comment]
@richelbilderbeek 
great, I clean up my code and then I'll join. cine sounds like a good branch name

**Comment by richelbilderbeek** [comment]
`cine` it is. You are a collaborator of [the pbdmms GitHub](https://github.com/richelbilderbeek/pbdmms). Do rename all your files to `cine_[something]`, e.g. `cine_main.cpp`.
